export default {
  actions: {
    CREATE_TASK: 'CREATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    TOGGLE_TASK_SELECTION: 'TOGGLE_TASK_SELECTION',
    TOGGLE_TASK_STATUS: 'TOGGLE_TASK_STATUS',
    SELECT_TASKS: 'SELECT_TASKS',
    DESELECT_TASKS: 'DESELECT_TASKS',
    DELETE_SELECTED_TASKS: 'DELETE_SELECTED_TASKS'
  }
}